name: Build ReCap Launcher (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check out sources
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          pacboy: gcc:p cmake:p make:p

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -AWin32 -G"Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=./dist

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --target install

      - uses: actions/upload-artifact@v4
        with:
          name: recap-launcher-windows-x86
          path: ${{runner.workspace}}/recap_launcher/build/dist
